# Generated by Django 5.0 on 2024-10-07 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection'), ('article', 'Article'), ('determiner', 'Determiner'), ('numeral', 'Numeral'), ('particle', 'Particle'), ('exclamation', 'Exclamation'), ('auxiliary', 'Auxiliary'), ('modal', 'Modal'), ('gerund', 'Gerund'), ('infinitive', 'Infinitive'), ('participle', 'Participle'), ('clause', 'Clause'), ('phrase', 'Phrase')], max_length=30)),
                ('definition', models.TextField()),
                ('examples', models.JSONField(blank=True, default=list, null=True)),
                ('synonyms', models.JSONField(blank=True, default=list, null=True)),
                ('antonyms', models.JSONField(blank=True, default=list, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='dictionary_app.word')),
            ],
        ),
    ]
