# Generated by Django 5.0 on 2024-10-15 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection'), ('article', 'Article'), ('determiner', 'Determiner'), ('numeral', 'Numeral'), ('particle', 'Particle'), ('exclamation', 'Exclamation'), ('auxiliary', 'Auxiliary'), ('modal', 'Modal'), ('gerund', 'Gerund'), ('infinitive', 'Infinitive'), ('participle', 'Participle'), ('clause', 'Clause'), ('phrase', 'Phrase')], max_length=30)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('antonyms', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField()),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('antonyms', models.JSONField(blank=True, default=list)),
                ('example', models.TextField(blank=True, null=True)),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='dictionary_app.meaning')),
            ],
        ),
        migrations.CreateModel(
            name='Phonetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('audio', models.URLField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('license', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phonetics', to='dictionary_app.license')),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('source_urls', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_entries', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictionary_entries', to='dictionary_app.license')),
                ('meanings', models.ManyToManyField(related_name='dictionary_entries', to='dictionary_app.meaning')),
                ('phonetics', models.ManyToManyField(related_name='dictionary_entries', to='dictionary_app.phonetic')),
            ],
        ),
    ]
