# Generated by Django 5.0 on 2024-10-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='example',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
