# Generated by Django 5.0 on 2024-10-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0002_alter_phonetic_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetic',
            name='text',
            field=models.URLField(blank=True, default=''),
        ),
    ]
