# Generated by Django 5.0 on 2024-10-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0002_alter_definition_example'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meaning',
            old_name='part_of_speech',
            new_name='partOfSpeech',
        ),
    ]
