# Generated by Django 5.0 on 2024-10-04 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0002_alter_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
