# Generated by Django 5.0 on 2024-10-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0004_alter_dictionaryentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
